---
stages:
    - deploy


deploy_app:
  stage: deploy
  script:
    - docker-compose -f docker-compose-prod.yml restart
    - docker-compose -f docker-compose-prod.yml up -d
  only:
    refs:
      - prod
      - master
